# Generated by Django 4.1.5 on 2023-01-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='password',
        ),
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
