# Generated by Django 4.1.5 on 2023-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogs_is_active_remove_blogs_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
