# Generated by Django 4.1.5 on 2023-01-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='referel_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='file',
            field=models.FileField(blank=True, upload_to='posts'),
        ),
    ]
