# Generated by Django 4.1.5 on 2023-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogs_referel_link_alter_blogs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_by',
            field=models.CharField(blank=True, max_length=266),
        ),
    ]
